// Code generated by thriftgo (0.3.2). DO NOT EDIT.

package java

import (
	"time"
)

type Object = interface{}

func NewObject() *Object {
	return nil
}

type Date = time.Time

func NewDate() *Date {
	return &Date{}
}
